add the old price on the product card
odevpl/wdp-2109-01 pull request #11
Opened 2021-09-09 13:28 UTC by agnieszka-f

2021-09-10 06:28 UTC, odevpl requested changes
Zapraszam do usunięcia konfliktów

2021-09-10 12:13 UTC, agnieszka-f reviewed
Konflikty usuniętę. Proszę o weryfikację.

2021-09-10 12:26 UTC, kai-mareving commented on src/components/common/ProductBox/ProductBox.js
> +          variant={favoritue ? 'favoritue' : 'outline'}
sugerowałabym podmianę nazwy zmiennej 'favoritue' i korespondującej z nią metody 'addToFavoritue' na 'favorite' i 'addToFavorite'. Taki malutki detal.

2021-09-10 12:34 UTC, kai-mareving reviewed
Wszystko wygląda w porządku. Sugerowałabym tylko podmianę nazwy zmiennej 'favoritue' na 'favorite' i metody 'AddToFavoritue' na 'AddToFavorite'. Oczywiście zmienione muszą wtedy być też zmienne w plikach redux etc.

2021-09-10 18:34 UTC, kai-mareving approved these changes

2021-09-11 13:57 UTC, agnieszka-f commented
Dzięki za zwrócenie uwagi na tą oczywistą literówkę. Poprawiłam ją wczoraj zgodnie z sugestią u siebie lokalnie lecz pojawił się problem z wypchnięciem tych zmian do zdalnego repo. Przy próbie git push origin WDP210901-11 pojawia się error z komunikatem aby wykonać git pull, a po wykonaniu git pull niestety utraciłam całą swoją pracę nad tym zadaniem i kolejnym zadaniem nad którym wczoraj pracowałam. Pracę odtworzyłam ale nadal mam problem z wypchnięciem tych zmian.

2021-09-11 15:24 UTC, kai-mareving commented
a co teraz blokuje pusha?

2021-09-12 06:46 UTC, merged