Wdp210901 9
odevpl/wdp-2109-01 pull request #26
Opened 2021-09-14 18:51 UTC by Robert-Roszak

Zadanie WDP210901-9 dotyczące jednolitych animacji zakończone. Czekam na feedback :)

2021-09-15 02:26 UTC, kai-mareving commented on src/components/common/Button/Button.module.scss
> +.favourite {
### favorite

2021-09-15 02:26 UTC, kai-mareving commented on src/components/common/Button/Button.module.scss
> +.outline, .favourite {
### favorite

2021-09-15 02:26 UTC, kai-mareving commented on src/components/common/ProductBox/ProductBox.js
> +  favourite,
### favorite

2021-09-15 02:27 UTC, kai-mareving commented on src/components/common/ProductBox/ProductBox.js
> +  addTofavourite,
### addToFavorite

2021-09-15 02:27 UTC, kai-mareving commented on src/components/common/ProductBox/ProductBox.js
> +          variant={favourite ? 'favourite' : 'outline'}
{favorite ? 'favorite' : 'outline'}

2021-09-15 02:28 UTC, kai-mareving commented on src/components/common/ProductBox/ProductBox.js
> +            return addTofavourite(id);
addToFavorite(id);

2021-09-15 02:28 UTC, kai-mareving commented on src/components/common/ProductBox/ProductBox.js
> +  favourite: PropTypes.bool,
favorite

2021-09-15 02:28 UTC, kai-mareving commented on src/components/common/ProductBox/ProductBox.js
> +  addTofavourite: PropTypes.func,
addToFavorite

2021-09-15 02:29 UTC, kai-mareving commented on src/components/common/ProductBox/ProductBoxContainer.js
> +import { getAll, addTofavourite } from '../../../redux/productsRedux.js';
addToFavorite

2021-09-15 02:29 UTC, kai-mareving commented on src/components/common/ProductBox/ProductBoxContainer.js
> +    addTofavourite: id => dispatch(addTofavourite(id)),
addToFavorite

2021-09-15 02:31 UTC, kai-mareving commented on src/redux/initialState.js
> +      favourite: true,
wszystkie wystąpienia favourite -> *favorite*

2021-09-15 02:33 UTC, kai-mareving commented on src/redux/productsRedux.js
> +export const ADD_TO_favourite = createActionName('ADD_TO_favourite');
export const ADD_TO_FAVORITE = createActionName('ADD_TO_FAVORITE');

2021-09-15 02:35 UTC, kai-mareving commented on src/redux/productsRedux.js
> +export const addTofavourite = payload => ({ payload, type: ADD_TO_favourite });
export const addToFavorite = payload => ({ payload, type: ADD_TO_FAVORITE });

2021-09-15 02:35 UTC, kai-mareving commented on src/redux/productsRedux.js
> +    case ADD_TO_favourite: {
case ADD_TO_FAVORITE: {

2021-09-15 02:36 UTC, kai-mareving commented on src/redux/productsRedux.js
> +          ? { ...product, favourite: !product.favourite }
? { ...product, favorite: !product.favorite }

2021-09-15 02:36 UTC, kai-mareving requested changes
Uwagi w komentarzach

2021-09-16 12:30 UTC, Robert-Roszak commented on src/components/common/ProductBox/ProductBox.module.scss
> -    &:hover {
Dodałem część tego kodu, hover był w złym miejscu a zmiana koloru tła wyglądała brzydko

2021-09-16 12:32 UTC, Robert-Roszak commented on src/redux/productsRedux.js
> +export const ADD_TO_favourite = createActionName('ADD_TO_favourite');
poprawione

2021-09-16 12:32 UTC, kai-mareving approved these changes

2021-09-16 12:32 UTC, Robert-Roszak commented on src/redux/productsRedux.js
> +export const addTofavourite = payload => ({ payload, type: ADD_TO_favourite });
poprawione

2021-09-16 12:33 UTC, Robert-Roszak commented on src/redux/productsRedux.js
> +    case ADD_TO_favourite: {
poprawione

2021-09-16 12:54 UTC, Robert-Roszak commented
@odevpl gotowe, możesz mergować ;)

2021-09-16 14:38 UTC, closed without merging

2021-09-16 14:38 UTC, Robert-Roszak commented
Errors, errors everywhere