saving the current RWD mode in the application state
odevpl/wdp-2109-01 pull request #27
Opened 2021-09-15 13:29 UTC by cinekenic

2021-09-15 20:57 UTC, odevpl commented on src/components/layout/MainLayout/MainLayout.js
> +  const [size, setSize] = useState(window.innerWidth);
Hej! Mam uwagę w temacie wydajności.
Zauważ, że przy lekkim przeciąganiu okna przeglądarki opka zmienia swój stan size kilkadziesiąt razy... może by tak ograniczyć zmianę tylko wtedy, gdy tylko tryb ulegnie zmianie, czyli:

jeśli obecny tryb = tablet, a szerokość jaką mam jest mniejsza, ale to nadal tablet, to nie robię setSize... 

sugerował bym bardziej setDevice, a nie set size :)

2021-09-15 20:58 UTC, odevpl requested changes
Mała propozycja zmiany kodu :) Obecna wersja może mocno mulić za chwilę

2021-09-16 15:21 UTC, cinekenic commented on src/components/layout/MainLayout/MainLayout.js
> +  const [size, setSize] = useState(window.innerWidth);
nie bardzo rozumiem, w stanie aplikacji mogą być tylko 'mobile', 'tablet' i 'desktop'. To event odpala się tak często ale to na nim jest ten mechanizm oparty, myślę, że to co mogę zrobić to setTimeout, żeby niwelować ilość odpalonych eventu, ale wtedy stan aplikacji też będzie się zmieniał z opóźnieniem. Jakieś koło ratunkowe by się przydało.

2021-09-16 20:35 UTC, odevpl commented on src/components/layout/MainLayout/MainLayout.js
> +  const [size, setSize] = useState(window.innerWidth);
Koło ratunkowe jest takie, że zapisujesz aktualne urządzenie w stanie apki. Po resize uruchamiasz ifa, który sprawdza, czy nowa szerokość, to to samo urządzenie, jeśli tak, to nic nie rób, jeśli nie, to zmień na nowe urządzenie. Koniec :)

2021-09-20 09:40 UTC, odevpl requested changes
Hej! Co z tym ticketem?

2021-09-20 10:51 UTC, MarcinSkowronek27 commented
Będę chciał zrobić dzisiaj CR, chociaż Robert nie poprawił jeszcze konfliktu.

2021-09-20 11:55 UTC, Robert-Roszak commented
> Będę chciał zrobić dzisiaj CR, chociaż Robert nie poprawił jeszcze konfliktu.

To Piotrka pull request ;) Też widzę, że nie zostały wprowadzone poprawki dlatego nie robiłem CR.

2021-09-20 12:52 UTC, cinekenic commented
Wypuściłem nowego commita, myślę, że teraz będzie ok.

2021-09-21 20:05 UTC, MarcinSkowronek27 approved these changes
Kod na piątkę :)

2021-09-22 11:00 UTC, merged