Wdp210901 35
odevpl/wdp-2109-01 pull request #35
Opened 2021-09-17 15:57 UTC by cinekenic

2021-09-18 17:58 UTC, KamilaKodilla reviewed
Dokonałam **code review** tylko **taska-WDP210901-35** dotyczącego dodania linków na stronie głównej. Na branchu przypisanym do tego zadania, znajduje się commit związany z innym zadaniem (wydaje mi się, że WDP210901-20). Mi też się to zdarzyło, przy zakładaniu gałęzi do mojego drugiego zadania, bo zapomniałam wcześniej wykonać checkout na mastera z poprzedniego 😊. 
1.	Code review rozpoczęłam od prześledzenia kodu. Jest starannie wpisany i nie budzi żadnych wątpliwości co do czytelności i poprawności rozwiązania. Znalazłam jedynie jeden zapis, przy którym zaproponowałam ujednolicenie (zaznaczyłam go w kodzie 😊).
2.	Po uruchomieniu podglądu strony sprawdziłam, czy wszystkie linki działają zgodnie z treścią zadania. Poruszanie po stronie przebiega prawidłowo, a wartości w linkach są widoczne.
3.	Jeśli mogę, chciałabym podpowiedzieć tylko jedną kwestię. Na pewno to zwykłe przeoczenie, ale przycisk blog zgodnie z treścią zadania powinien kierować do pustej podstrony, którą trzeba stworzyć 😊.
Mam nadzieję, że nie sprawię kłopotu swoimi uwagami, a troszkę wesprę to bardzo dobrze wykonane zadanie 😊.

2021-09-18 17:58 UTC, KamilaKodilla commented on src/components/layout/MenuBar/MenuBar.js
> +                <a href='/shop/furniture'>Furniture</a>
Może warto byłoby ujednolicić tę linijkę do pozostałych linków. Czyli <Link exact to={'shop/furniture'} replace>Futniture</Link> :)

2021-09-19 08:26 UTC, odevpl requested changes
Hej! Jest tu bardzo dużo zmian, a ticket miał tylko dotyczyć nawigacji... Zrób nowego brancha prosto z mastera i wrzuć tylko tę funkcjonalność, która dotyczy nawigacji.

2021-09-19 12:33 UTC, cinekenic commented
> Hej! Jest tu bardzo dużo zmian, a ticket miał tylko dotyczyć nawigacji... Zrób nowego brancha prosto z mastera i wrzuć tylko tę funkcjonalność, która dotyczy nawigacji.

Tak jak pisałem, zapomniałem zrobić rebase, ilość tych zmian wynika z tego, że master teraz tak wygląda (bez nawigacji która jecze wisi ponieważ jest konflikt z innym commitem który jest w trakcie poprawek).

2021-09-19 12:38 UTC, cinekenic commented
> Dokonałam **code review** tylko **taska-WDP210901-35** dotyczącego dodania linków na stronie głównej. Na branchu przypisanym do tego zadania, znajduje się commit związany z innym zadaniem (wydaje mi się, że WDP210901-20). Mi też się to zdarzyło, przy zakładaniu gałęzi do mojego drugiego zadania, bo zapomniałam wcześniej wykonać checkout na mastera z poprzedniego 😊.
> 
> 1. Code review rozpoczęłam od prześledzenia kodu. Jest starannie wpisany i nie budzi żadnych wątpliwości co do czytelności i poprawności rozwiązania. Znalazłam jedynie jeden zapis, przy którym zaproponowałam ujednolicenie (zaznaczyłam go w kodzie 😊).
> 2. Po uruchomieniu podglądu strony sprawdziłam, czy wszystkie linki działają zgodnie z treścią zadania. Poruszanie po stronie przebiega prawidłowo, a wartości w linkach są widoczne.
> 3. Jeśli mogę, chciałabym podpowiedzieć tylko jedną kwestię. Na pewno to zwykłe przeoczenie, ale przycisk blog zgodnie z treścią zadania powinien kierować do pustej podstrony, którą trzeba stworzyć 😊.
>    Mam nadzieję, że nie sprawię kłopotu swoimi uwagami, a troszkę wesprę to bardzo dobrze wykonane zadanie 😊.

Dzięki za poświęcony czas na analizę, faktycznie jest tam jeszcze jeden commit który wisi ponieważ mam tam do zrobienia poprawkę od PM-a z którą walczę. Co do bloga to wydawało mi się, że właśnie tak ma to wyglądać na tym etapie.

2021-09-20 09:53 UTC, odevpl commented
> > Dokonałam **code review** tylko **taska-WDP210901-35** dotyczącego dodania linków na stronie głównej. Na branchu przypisanym do tego zadania, znajduje się commit związany z innym zadaniem (wydaje mi się, że WDP210901-20). Mi też się to zdarzyło, przy zakładaniu gałęzi do mojego drugiego zadania, bo zapomniałam wcześniej wykonać checkout na mastera z poprzedniego 😊.
> > 
> > 1. Code review rozpoczęłam od prześledzenia kodu. Jest starannie wpisany i nie budzi żadnych wątpliwości co do czytelności i poprawności rozwiązania. Znalazłam jedynie jeden zapis, przy którym zaproponowałam ujednolicenie (zaznaczyłam go w kodzie 😊).
> > 2. Po uruchomieniu podglądu strony sprawdziłam, czy wszystkie linki działają zgodnie z treścią zadania. Poruszanie po stronie przebiega prawidłowo, a wartości w linkach są widoczne.
> > 3. Jeśli mogę, chciałabym podpowiedzieć tylko jedną kwestię. Na pewno to zwykłe przeoczenie, ale przycisk blog zgodnie z treścią zadania powinien kierować do pustej podstrony, którą trzeba stworzyć 😊.
> >    Mam nadzieję, że nie sprawię kłopotu swoimi uwagami, a troszkę wesprę to bardzo dobrze wykonane zadanie 😊.
> 
> Dzięki za poświęcony czas na analizę, faktycznie jest tam jeszcze jeden commit który wisi ponieważ mam tam do zrobienia poprawkę od PM-a z którą walczę. Co do bloga to wydawało mi się, że właśnie tak ma to wyglądać na tym etapie.


Generalnie problem polega na tym, że zrobiłeś RWD, potem nie wróciłeś do mastera, tylko z brancha z RWD zrobiłeś ten z linkami :)

Jedyne wyjście z sytuacji, to skasować drugi commit z RWD... Pomogę Ci z tym

2021-09-20 10:05 UTC, odevpl commented
Skasowałem niepotrzebne commity. Skasuj brancha za pomocą git branch -D WDP210901-35
Potem zrób git pull i wskocz ponownie na brancha. Następnie zajmij się konfliktami i jesteśmy w domu

2021-09-20 15:48 UTC, cinekenic commented
Zrobiłem git branch -D WDP210901-35, następnie pull i rebase. i usunąłem konflikty. W terminalu, po rebase, dostałem komunikat, że "Everything up-to-date". Mam nadzieję, że to tak miał być.

2021-09-20 19:36 UTC, merged