Rwd-16
odevpl/wdp-2109-01 pull request #5
Opened 2021-09-08 19:08 UTC by MarcinSkowronek27

TASK WDP210901-16 - task dotyczy kart korzyści ("Free shipping", etc.).
Klient chce w trybach tablet i mobile mieć je w 2 rzędach, po 2 elementy w każdym; elementy w jednym rzędzie (obok siebie) nie powinny się różnić wysokością. 
Zadanie wykonane - zastosowano komponent Grid w React oraz dodano odpowiednie style.

2021-09-10 06:09 UTC, odevpl requested changes
Zerknij na komentarze i popraw je proszę

2021-09-10 06:09 UTC, odevpl commented on src/components/features/FeatureBoxes/FeatureBoxes.js
> +    {/* <div className='container'> */}
Jeśli tego nie chcemy, to do kosza z tym :)

2021-09-10 06:09 UTC, odevpl commented on src/components/features/FeatureBoxes/FeatureBoxes.js
> +    {/* <div className='row'> */}
Jak wyżej

2021-09-10 06:09 UTC, odevpl commented on src/components/features/FeatureBoxes/FeatureBoxes.js
> +        {/* </div> */}
Obydwa do kosza

2021-09-10 06:09 UTC, odevpl commented on package.json
> +    "node-sass": "4",
Ta zmiana była konieczna? Format wersji trochę się nie zgadza

2021-09-10 11:08 UTC, MarcinSkowronek27 commented
Wrzuciłem poprawiony kod. Jeżeli chodzi o node-sass miałem problem z otworzeniem projektu w przeglądarce - wyrzucał problem niezgodności wersji właśnie node-sass, że była "za wysoka" do innej paczki (ale nie podawał konkretnie jakiej). Jak zainstalowałem wersję 4 to działa dobrze. Nie wiem natomiast, jak rozwiązać konflikt z plikiem yarn.lock?

2021-09-12 19:32 UTC, odevpl requested changes
Poprawki w komentarzach.

2021-09-12 19:32 UTC, odevpl commented on src/components/common/ProductBox/ProductBox.js
> +  isStarred,
Usuń przecinek!!!!

2021-09-14 14:55 UTC, MarcinSkowronek27 commented on src/components/features/FeatureBoxes/FeatureBoxes.js
> +    {/* <div className='container'> */}
poprawione ;)

2021-09-14 14:55 UTC, MarcinSkowronek27 commented on src/components/features/FeatureBoxes/FeatureBoxes.js
> +        {/* </div> */}
poprawione ;)

2021-09-14 14:55 UTC, MarcinSkowronek27 commented on package.json
> +    "node-sass": "4",
wyjaśnione; tak była konieczna ;)

2021-09-15 20:37 UTC, merged