WDP210901-42
odevpl/wdp-2109-01 pull request #59
Opened 2021-09-21 19:50 UTC by Robert-Roszak

Przegląd produktu na podstronie /product/

2021-09-22 13:23 UTC, kai-mareving requested changes
Komponent przygotowany bardzo ładnie i ogólnie dobrze z drobnymi uwagami, które zostawiam w komentarzach.

2021-09-22 13:23 UTC, kai-mareving commented on src/components/views/ProductPage/ProductPage.js
> +                        value={item.quantity}
Konsola sypie warningiem:
_Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`._

Zrób ten input tak:

```
                  <input
                        type='text'
                        id='quantity'
                        name='quantity'
                        readOnly //remove when adding functionality
                        value={item.quantity}
                        className={styles.quantityInput}
                      />
```

2021-09-22 13:23 UTC, kai-mareving commented on src/components/views/ProductPage/ProductPage.module.scss
> +@import "./../../../styles/settings.scss";
`@import '../../../styles/settings.scss';`

2021-09-22 13:23 UTC, kai-mareving commented on src/components/views/ProductPage/ProductPage.module.scss
> +          }
Te buttony trzeba by inaczej ostylować bo wedle załącznika do taska mają wyglądać tak:
![image](https://user-images.githubusercontent.com/23086654/134349945-8e65200b-7c89-44be-a567-203a21a6e20c.png)

Proponuję w ProductPage.js użyć w gridzie .socialMedia <Button/> zamiast zwykłych html'owych <button> a konkretniej np. <Button variant='small' /> a najlepiej dorobić w Button.module.js specjalną klasę-wariant na te buttony. Niech extenduje np .small i dodaje odpowiednie właściwości.

2021-09-23 10:14 UTC, Robert-Roszak commented on src/components/views/ProductPage/ProductPage.js
> +  products: PropTypes.array,
Dodane w nowym commicie :)

2021-09-23 10:16 UTC, Robert-Roszak commented on src/components/views/ProductPage/ProductPage.module.scss
> +@import "./../../../styles/settings.scss";
Ostatecznie efekt ten sam, ale słuszna uwaga :)

2021-09-23 10:17 UTC, Robert-Roszak commented on src/components/views/ProductPage/ProductPage.js
> +                        value={item.quantity}
Ciekawe, bo w momencie w którym wrzucałem commit miałem tam defaultValue={item.quantity} a teraz tego nie ma.. Oba rozwiązania są dobre :)

2021-09-23 10:20 UTC, Robert-Roszak commented on src/components/views/ProductPage/ProductPage.module.scss
> +          }
Hmm nad tym miałem długą zagwozdkę, ostatecznie stwierdziłem, że skopuje je z dołu strony. Celem tego było zachowanie spójności styli.
@odevpl co myślisz? Jeżeli ma być wg projektu, proponuję już zrobić merge tego pull requestu i dorobić nowy ticket na ostylowanie tych przycisków wg projektu. W tym momencie zajmuję się innym ticketem, a cały ten komponent jest dosyć ważny do dalszych prac.

2021-09-23 10:33 UTC, Robert-Roszak commented
@odevpl jeden komentarz dotyczy ikonek social media i potrzebna jest decyzja PMa :)

2021-09-24 19:25 UTC, merged