Wdp210901 5
odevpl/wdp-2109-01 pull request #6
Opened 2021-09-08 20:36 UTC by ffrysz

Przycisku stanu w karcie produktu mają teraz możliwość otrzymania klasy 'active'. Zaprezentowano to na 3 wybranych produktach.

2021-09-10 06:24 UTC, odevpl requested changes
Hej!
Niestety pojawiły się konflikty

2021-09-14 21:16 UTC, ffrysz commented
Problemy powinny być usunięte. Po otwarciu strony powinien być jeden produkt z aktywnym przyciskiem "favourite", jeden z "compare" i jeden z obydwoma.

2021-09-16 20:28 UTC, odevpl requested changes
Hej! Czemu 29 i 40 commitów?
Co to się stanęło?

2021-09-16 20:38 UTC, ffrysz commented
Hmm, zrobiłem rebase z mastera i zaciągnęło tyle. Może coś źle zrobiłem bo to był mój pierwszy rebase :D

2021-09-17 05:55 UTC, closed without merging