Wdp210901-85
odevpl/wdp-2109-01 pull request #93
Opened 2021-09-27 19:49 UTC by MarcinSkowronek27

Dostosuj sekcję deals, by odpowiednio pokazywała się we wszystkich szerokościach ekranu

2021-09-27 20:13 UTC, MarcinSkowronek27 commented
Konflikty usunięte.

2021-09-28 12:49 UTC, kai-mareving requested changes
Drobne sugestie zamieszczam w komentarzach. Chodzi wyłącznie o dopieszczenie bo ogólnie jest bardzo dobrze zrobione. Brawo 🥂 !

2021-09-28 12:49 UTC, kai-mareving commented on src/components/layout/Deals/Deals.module.scss
> +  }
```suggestion
  }
  .root .wrapperRight .wrapperSmall {
    width: 90%;
  }
```

2021-09-28 12:49 UTC, kai-mareving commented on src/components/layout/Deals/Deals.module.scss
> +}
```suggestion
@media screen and (max-width: 473px){
  .root .wrapperLeft .greyBox {
    left: 33px;
  }
  .root .wrapperRight .priceTitleTwo {
    right: 130px;
  }
  .root .wrapperRight .wrapperSmall {
    padding-bottom: 0 !important;
  }
  .root .wrapperRight .wrapperSmall img {
    height: 80%;
  }
}
```

2021-09-28 12:49 UTC, kai-mareving commented on src/components/layout/Deals/Deals.module.scss
> +  .root .wrapperRight .priceTitleTwo {
Co sądzisz o tym żeby zmniejszyć ogólny rozmiar czcionki w `.priceTitleTwo` i `.priceTitleThree` przy tej rozdzielczości? Myślę, że wyglądałoby lepiej.

2021-09-28 12:49 UTC, kai-mareving commented on src/components/layout/Deals/Deals.module.scss
> +    left: 29px;
```suggestion
    left: 28px;
```

2021-09-28 16:41 UTC, MarcinSkowronek27 commented on src/components/layout/Deals/Deals.module.scss
> +    left: 29px;
Dobry pomysł.

2021-09-28 16:42 UTC, MarcinSkowronek27 commented
Poprawki uwzględnione ;)

2021-09-28 17:35 UTC, merged